services:
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: user-management-service
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:4.4
    container_name: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
